# Generated by Django 6.0.7 on 2026-07-18 04:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('welcome', 'Welcome'), ('pass_changed', 'Password Changed'), ('account_blocked', 'Account Blocked'), ('new_user_joined', 'New User Joined')], db_index=True, max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('websocket_pushed', models.BooleanField(default=False, help_text='True when a real-time WebSocket push was attempted (admin only).')),
                ('websocket_success', models.BooleanField(default=False, help_text='True when the WebSocket push was confirmed sent (admin only).')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
