# Generated by Django 6.0.7 on 2026-07-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('pass_changed', 'Password Changed'), ('account_blocked', 'Account Blocked'), ('account_reactivated', 'Account Reactivated'), ('profile_completed', 'Profile Completed'), ('onboarding_completed', 'Onboarding Completed'), ('plan_saved', 'Plan Saved'), ('plan_reminder', 'Plan Reminder'), ('event_starting_soon', 'Event Starting Soon'), ('subscription_upgraded', 'Subscription Upgraded'), ('subscription_expiring', 'Subscription Expiring'), ('subscription_expired', 'Subscription Expired'), ('payment_failed', 'Payment Failed'), ('ai_recommendation_ready', 'AI Recommendation Ready'), ('system_announcement', 'System Announcement'), ('new_user_joined', 'New User Joined'), ('admin_broadcast', 'Admin Broadcast')], db_index=True, max_length=60),
        ),
    ]
