# Generated by Django 6.0.7 on 2026-07-18 04:52

import apps.users.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='Full Name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='User sets gender on Onboarding', max_length=10, null=True, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/profile_pictures/', verbose_name='Profile Picture')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('interests', models.JSONField(blank=True, null=True, verbose_name='Interests')),
                ('budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='Budget')),
                ('subscription_plan', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='free', max_length=20, verbose_name='Subscription Plan')),
                ('subscription_start', models.DateTimeField(blank=True, null=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('self', 'Self'), ('google', 'Google'), ('apple', 'Apple')], default='self', max_length=20, verbose_name='Auth Provider')),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False = account is blocked (by admin) ', verbose_name='Active')),
                ('device_token', models.CharField(blank=True, help_text='FCM/APNs device token for push notifications.', max_length=255, null=True, verbose_name='Device Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
